/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rms;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rajat
 */
public class CASHIER_DASHBOARD extends javax.swing.JFrame implements Connectivity {

    /**
     * Creates new form CASHIER_DASHBOARD
     */
   private void animate(String customer)
   {
       ITEM_SELECTION ob = new ITEM_SELECTION(username,customer);
       ob.setVisible(true);
   }
    private void update(JTable ob)
    {
        ob.getTableHeader().setFont(new Font("Bahnschrift", Font.BOLD, 14));
        try
        { 
            Connection cn=Connectivity.getConnection();
            PreparedStatement ps=cn.prepareStatement("select * from Customer");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)ob.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {   
                Object o[]={rs.getString("CID"),rs.getString("CName"),rs.getString("TPNo"),rs.getString("Address")};
                tm.addRow(o);
            }
        }
    catch(Exception e)
    {   
        JOptionPane.showMessageDialog(this,e);
    }
    }
    private void update2(JTable ob)
    {
        ob.getTableHeader().setFont(new Font("Bahnschrift", Font.BOLD, 14));
        try
        { 
            Connection cn=Connectivity.getConnection();
            PreparedStatement ps=cn.prepareStatement("select * from orders");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)ob.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {   
                Object o[]={rs.getString("OrderID"),rs.getString("OrderDate"),rs.getString("Amount"),rs.getString("CID"),rs.getString("Discount"),rs.getString("OrderStatus")};
                tm.addRow(o);
            }
        }
    catch(Exception e)
    {   
        JOptionPane.showMessageDialog(this,e);
    }
    }
    public CASHIER_DASHBOARD(String username) {
        this.username=username;
        initComponents();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ORDER.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        try
        {
            Statement stmt = connectdata();
            ResultSet rs = stmt.executeQuery("Select LName from login where LUser = '"+ username +"'");
            rs.next();
            String user =rs.getString(1);

            rs = stmt.executeQuery("Select LType from login where LUser = '"+ username +"'");
            rs.next();
            String type=rs.getString(1);
            jLabel1.setText("WELCOME, "+user+"("+type+")");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        update(jTable1);
        update(jTable2);
        update2(ORDER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        dr = new javax.swing.JLabel();
        HEADER2 = new javax.swing.JLabel();
        YES = new javax.swing.JButton();
        NO = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        SELECTION = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MC = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        TO = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        VO = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        VO1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        LOGOUT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HEADER = new javax.swing.JLabel();
        PANEL = new javax.swing.JPanel();
        A = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        cid = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        ph = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        B = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        TO_SEL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        HEADER1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        TO_GOTO = new javax.swing.JButton();
        C = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ORDER = new javax.swing.JTable();
        D = new javax.swing.JPanel();

        jDialog1.setTitle("Message");
        jDialog1.setIconImage(new ImageIcon(getClass().getResource("image/icons8_box_important_60px_1.png")).getImage());

        dr.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        dr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        HEADER2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        HEADER2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADER2.setText("DELETE THE FOLLOWING RECORD:");

        YES.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        YES.setText("YES");
        YES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YESActionPerformed(evt);
            }
        });

        NO.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        NO.setText("NO");
        NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HEADER2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addComponent(dr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(YES, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NO, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(HEADER2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dr, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YES, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Client Server");
        setIconImage(new ImageIcon(getClass().getResource("image/icon.png")).getImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SELECTION.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        MC.setBackground(new java.awt.Color(0, 0, 0));
        MC.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        MC.setForeground(new java.awt.Color(255, 255, 255));
        MC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/image/mc.png"))); // NOI18N
        MC.setText(" Manage Customer");
        MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCActionPerformed(evt);
            }
        });

        TO.setBackground(new java.awt.Color(0, 0, 0));
        TO.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        TO.setForeground(new java.awt.Color(255, 255, 255));
        TO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/image/TO.png"))); // NOI18N
        TO.setText("    Take Order");
        TO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOActionPerformed(evt);
            }
        });

        VO.setBackground(new java.awt.Color(0, 0, 0));
        VO.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        VO.setForeground(new java.awt.Color(255, 255, 255));
        VO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/image/VO.png"))); // NOI18N
        VO.setText(" View Orders");
        VO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOActionPerformed(evt);
            }
        });

        VO1.setBackground(new java.awt.Color(0, 0, 0));
        VO1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        VO1.setForeground(new java.awt.Color(255, 255, 255));
        VO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/image/PO.png"))); // NOI18N
        VO1.setText(" Pending Orders");
        VO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VO1ActionPerformed(evt);
            }
        });

        LOGOUT.setBackground(new java.awt.Color(255, 0, 0));
        LOGOUT.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/image/ic_launcher.png"))); // NOI18N

        javax.swing.GroupLayout SELECTIONLayout = new javax.swing.GroupLayout(SELECTION);
        SELECTION.setLayout(SELECTIONLayout);
        SELECTIONLayout.setHorizontalGroup(
            SELECTIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SELECTIONLayout.createSequentialGroup()
                .addGroup(SELECTIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SELECTIONLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SELECTIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VO1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MC, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(TO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SELECTIONLayout.createSequentialGroup()
                        .addGroup(SELECTIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SELECTIONLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SELECTIONLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(SELECTIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELECTIONLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SELECTIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELECTIONLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELECTIONLayout.createSequentialGroup()
                        .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
            .addGroup(SELECTIONLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SELECTIONLayout.setVerticalGroup(
            SELECTIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SELECTIONLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(MC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VO1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(SELECTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 730));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/image/RES_LOGO.png"))); // NOI18N

        HEADER.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        HEADER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADER.setText("Cashier Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(810, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(HEADER)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1010, 130));

        PANEL.setLayout(new java.awt.CardLayout());

        A.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CID");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");

        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton3.setText("Get Selected");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cid.setBackground(new java.awt.Color(0, 0, 0));
        cid.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        cid.setForeground(new java.awt.Color(255, 255, 255));
        cid.setBorder(null);

        cn.setBackground(new java.awt.Color(0, 0, 0));
        cn.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        cn.setForeground(new java.awt.Color(255, 255, 255));
        cn.setBorder(null);

        ph.setBackground(new java.awt.Color(0, 0, 0));
        ph.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        ph.setForeground(new java.awt.Color(255, 255, 255));
        ph.setBorder(null);
        ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phActionPerformed(evt);
            }
        });

        addr.setBackground(new java.awt.Color(0, 0, 0));
        addr.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        addr.setForeground(new java.awt.Color(255, 255, 255));
        addr.setBorder(null);

        jButton5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton5.setText("VIEW ALL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jSeparator9)
                                    .addComponent(ph))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addr, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator8))
                                        .addContainerGap())))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(5, 5, 5)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CID", "CName", "Phone Number", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ALayout = new javax.swing.GroupLayout(A);
        A.setLayout(ALayout);
        ALayout.setHorizontalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ALayout.setVerticalGroup(
            ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        PANEL.add(A, "card2");

        B.setBackground(new java.awt.Color(204, 204, 204));

        TO_SEL.setBackground(new java.awt.Color(0, 0, 0));
        TO_SEL.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        TO_SEL.setForeground(new java.awt.Color(255, 255, 255));
        TO_SEL.setText("SELECT");
        TO_SEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TO_SELActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "CName", "Phone Number", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);

        HEADER1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        HEADER1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HEADER1.setText("Customer Selection");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HEADER1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(TO_SEL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(HEADER1)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(TO_SEL)
                .addGap(23, 23, 23))
        );

        TO_GOTO.setBackground(new java.awt.Color(0, 0, 0));
        TO_GOTO.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        TO_GOTO.setForeground(new java.awt.Color(255, 255, 255));
        TO_GOTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rms/image/VO.png"))); // NOI18N
        TO_GOTO.setText("Go To Item Selection Menu");
        TO_GOTO.setActionCommand("");
        TO_GOTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TO_GOTOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(TO_GOTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(419, 419, 419))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(TO_GOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BLayout = new javax.swing.GroupLayout(B);
        B.setLayout(BLayout);
        BLayout.setHorizontalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BLayout.setVerticalGroup(
            BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PANEL.add(B, "card3");

        ORDER.setBackground(new java.awt.Color(0, 0, 0));
        ORDER.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        ORDER.setForeground(new java.awt.Color(255, 255, 255));
        ORDER.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Date", "Amount", "CID", "Discount Applied", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ORDER.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ORDER.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ORDER.setRowHeight(25);
        jScrollPane3.setViewportView(ORDER);

        javax.swing.GroupLayout CLayout = new javax.swing.GroupLayout(C);
        C.setLayout(CLayout);
        CLayout.setHorizontalGroup(
            CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        CLayout.setVerticalGroup(
            CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        PANEL.add(C, "card4");

        D.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout DLayout = new javax.swing.GroupLayout(D);
        D.setLayout(DLayout);
        DLayout.setHorizontalGroup(
            DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        DLayout.setVerticalGroup(
            DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        PANEL.add(D, "card5");

        jPanel1.add(PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 1010, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1352, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCActionPerformed
        HEADER.setText("Manage Customers in this window.");
        PANEL.removeAll();
        PANEL.add(A);
        PANEL.repaint();
        PANEL.revalidate();
    }//GEN-LAST:event_MCActionPerformed

    private void TOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOActionPerformed
        HEADER.setText("Initiate Orders.");
        PANEL.removeAll();
        PANEL.add(B);
        PANEL.repaint();
        PANEL.revalidate();
    }//GEN-LAST:event_TOActionPerformed

    private void VOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOActionPerformed
        HEADER.setText("View All Orders in the database.");
        PANEL.removeAll();
        PANEL.add(C);
        PANEL.repaint();
        PANEL.revalidate();
    }//GEN-LAST:event_VOActionPerformed

    private void VO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VO1ActionPerformed
        HEADER.setText("View and complete pending orders.");
        PANEL.removeAll();
        PANEL.add(D);
        PANEL.repaint();
        PANEL.revalidate();
    }//GEN-LAST:event_VO1ActionPerformed

    private void phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    if(cid.getText().equals("") || cn.getText().equals("") || ph.getText().equals("") || addr.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this,"ENTER ALL FIELDS");
        cid.setText("");cn.setText(username);ph.setText("");addr.setText("");
    }   
    else{
    try{        
    Connection con=Connectivity.getConnection();
    String sql ="insert into Customer(CID,CName,TPNo,Address) values (?,?,?,?)";
    PreparedStatement ps=con.prepareStatement(sql);
    ps.setString(1,cid.getText());
    ps.setString(2,cn.getText());
    ps.setString(3,ph.getText());
    ps.setString(4,addr.getText());
    ps.execute();
    JOptionPane.showMessageDialog(this,"Saved Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
     cid.setText("");cn.setText(username);ph.setText("");addr.setText("");
     update(jTable1);
     update(jTable2);
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(cid.getText().equals(""))
        JOptionPane.showMessageDialog(this,"ENTER CID TO SEARCH RECORDS");
       else
       {
         try
         { 
            Connection cn=Connectivity.getConnection();
            PreparedStatement ps=cn.prepareStatement("select * from Customer where CID ='"+cid.getText()+"'");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            tm.setRowCount(0);
            if (rs.next() == false)
            {
                JOptionPane.showMessageDialog(this,"NO RECORDS FOUND");
                tm.addRow(new Object[4]);
                return;
            }
            rs.beforeFirst();
            while(rs.next())
            {   
                Object o[]={rs.getString("CID"),rs.getString("CName"),rs.getString("TPNo"),rs.getString("Address")};
                tm.addRow(o);
            }
         }
            catch(Exception e)
            {   
                JOptionPane.showMessageDialog(this,e);
            }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     update(jTable1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
       this.dispose();
       LOGIN_CASHIER.main(new String [] {});
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jTable1.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(this,"PLEASE SELECT A TUPLE TO CONTINUE!");
            return;
        }
       else
       {
           
           int row = jTable1.getSelectedRow();
           String value = "CID : "+jTable1.getModel().getValueAt(row,0).toString()+
            "\n CName : "+jTable1.getModel().getValueAt(row,1).toString()+
            "\n TPNo: "+jTable1.getModel().getValueAt(row,2).toString()+
            "\n Address: "+jTable1.getModel().getValueAt(row,3).toString();
           dr.setText(value);
           
           jDialog1.setLocationRelativeTo(null);
           jDialog1.setSize(750,210);
           jDialog1.setVisible(true);
           jDialog1.setEnabled(true);
           this.setEnabled(false);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(jTable1.getSelectionModel().isSelectionEmpty())
       {
           JOptionPane.showMessageDialog(this,"NO TUPLE SELECTED!");
       }
       else
       {
           int row = jTable1.getSelectedRow();
           String value = "CID : "+jTable1.getModel().getValueAt(row,0).toString()+
                          "\nCName : "+jTable1.getModel().getValueAt(row,1).toString()+
                          "\nTPNo: "+jTable1.getModel().getValueAt(row,2).toString()+
                          "\nAddress : "+jTable1.getModel().getValueAt(row,3).toString();
           JOptionPane.showMessageDialog(this,value);
        
       }    
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TO_SELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TO_SELActionPerformed
       if(jTable2.getSelectionModel().isSelectionEmpty())
       {
           JOptionPane.showMessageDialog(this,"NO TUPLE SELECTED!");
       }
       else
       {
           int row = jTable2.getSelectedRow();
           String value = "FOLLOWING CUSTOMER SELECTED:\nCID : "+jTable2.getModel().getValueAt(row,0).toString()+
                          "\nCName : "+jTable2.getModel().getValueAt(row,1).toString()+
                          "\nTPNo: "+jTable2.getModel().getValueAt(row,2).toString()+
                          "\nAddress : "+jTable2.getModel().getValueAt(row,3).toString();
           JOptionPane.showMessageDialog(this,value);
        
       }
    }//GEN-LAST:event_TO_SELActionPerformed

    private void TO_GOTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TO_GOTOActionPerformed
        if(jTable2.getSelectionModel().isSelectionEmpty())
       {
           JOptionPane.showMessageDialog(this,"NO TUPLE SELECTED!");
       }
       else
       {
           int row = jTable2.getSelectedRow();
           String value = "FOLLOWING CUSTOMER SELECTED:\nCID : "+jTable2.getModel().getValueAt(row,0).toString()+
                          "\nCName : "+jTable2.getModel().getValueAt(row,1).toString()+
                          "\nTPNo: "+jTable2.getModel().getValueAt(row,2).toString()+
                          "\nAddress : "+jTable2.getModel().getValueAt(row,3).toString();
           JOptionPane.showMessageDialog(this,value);
           this.dispose();
           animate(jTable2.getModel().getValueAt(row,0).toString());
        
       }
    }//GEN-LAST:event_TO_GOTOActionPerformed

    private void YESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YESActionPerformed
        this.setEnabled(true);

        int row = jTable1.getSelectedRow();
        if(!jTable1.getSelectionModel().isSelectionEmpty())
        {
            String user = jTable1.getModel().getValueAt(row, 0).toString();
            try
            {
                Connection con=Connectivity.getConnection();
                PreparedStatement ps=con.prepareStatement("delete from customer where CID=?");
                ps.setString(1,user);
                int status=ps.executeUpdate();
                con.close();
            }
            catch(Exception e){ JOptionPane.showMessageDialog(this,e);}
        }

        update(jTable1);
        update(jTable2);
        jDialog1.dispose();
        return;
    }//GEN-LAST:event_YESActionPerformed

    private void NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOActionPerformed
        this.setEnabled(true);
        update(jTable1);
        jDialog1.dispose();
        return;
    }//GEN-LAST:event_NOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CASHIER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CASHIER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CASHIER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CASHIER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CASHIER_DASHBOARD(username).setVisible(true);
            }
        });
    }
    static String username;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A;
    private javax.swing.JPanel B;
    private javax.swing.JPanel C;
    private javax.swing.JPanel D;
    private javax.swing.JLabel HEADER;
    private javax.swing.JLabel HEADER1;
    private javax.swing.JLabel HEADER2;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton MC;
    private javax.swing.JButton NO;
    private javax.swing.JTable ORDER;
    private javax.swing.JPanel PANEL;
    private javax.swing.JPanel SELECTION;
    private javax.swing.JButton TO;
    private javax.swing.JButton TO_GOTO;
    private javax.swing.JButton TO_SEL;
    private javax.swing.JButton VO;
    private javax.swing.JButton VO1;
    private javax.swing.JButton YES;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cn;
    private javax.swing.JLabel dr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField ph;
    // End of variables declaration//GEN-END:variables
}
